export const TICK_SIMULATION = 'TICK_SIMULATION';
export const ADVANCE_TO_COMPLETION = 'ADVANCE_TO_COMPLETION';
export const PAUSE_SIMULATION = 'PAUSE_SIMULATION';
export const START_SIMULATION = 'START_SIMULATION';
export const RESET_SIMULATION = 'RESET_SIMULATION';
